version: '3'

### Networks ###############################################

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

### Volumes ###############################################
volumes:
  mysql:
    driver: local
  redis:
    driver: local
  www-data:
    driver: local

### Services ###############################################
services:

### Worspace #################################################
  workspace:
    build: ./workspace
    image: baotd86/workspace
    volumes:
      - ../web:/var/www/html:cached
    extra_hosts:
      - "dockerhost:10.0.75.1"    
    tty: true
    environment:
      - PHP_IDE_CONFIG=lemdock
    networks:
      - frontend
      - backend

### Account Service #################################################
  account-service:
    build: ./nginx
    image: baotd86/nginx
    volumes:
      - ../account-service:/var/www/html:cached
      - ./logs/nginx/:/var/log/nginx
      - ./nginx/sites/:/etc/nginx/sites-available
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    networks:
      - backend
      - frontend
### Aircraft Service #################################################
  aircraft-service:
    build: ./nginx
    image: baotd86/nginx
    volumes:
      - ../aircaft-service:/var/www/html:cached
      - ./logs/nginx/:/var/log/nginx
      - ./nginx/sites/:/etc/nginx/sites-available
    ports:
      - "8081:80"
    depends_on:
      - php-fpm
    networks:
      - backend
      - frontend
### PHP-PFM #################################################      
  php-fpm:
    build: ./php-fpm
    image: baotd86/php-fpm
    volumes:
      - ./php-fpm/php7.1.ini:/usr/local/etc/php/php.ini
      - www-data:/var/www/html
    expose:
      - "9000"
    extra_hosts:
      - "dockerhost:10.0.75.1"
    networks:
      - backend

### MySQL #################################################
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=5.7
    image: baotd86/mysql
    environment:
      - MYSQL_DATABASE=phpdock
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - TZ=UTC
    volumes:
      - ./database/mysql:/var/lib/mysql      
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - backend

### Redis ################################################
  redis:
    build: ./redis
    image: baotd86/redis
    volumes:
      - ./database/redis:/data
    ports:
      - "6379:6379"
    networks:
      - backend